pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/dinesh11990/Jenkins_DevOps'
            }
        }

        stage('Compile') {
            steps {
                sh 'javac HelloWorld.java'
            }
        }

        stage('Run') {
            steps {
                sh 'java HelloWorld'
            }
        }
    }
}
